contact_links:
  - name: Discussions
    url: https://github.com/bigscience-workshop/lam/discussions
    about: Please participate in discussions, ask and answer questions, and engage with other community members
